---
title: "3.1 — Immigration — Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

*Tuesday, November 10, 2020*

# Readings

- [<i class="fas fa-file-pdf"></i> Clemens, 2006, "Economics and Emigration: Trillion-Dollar Bills on the Sidewalk?"](/readings/Clemens-2006.pdf)
- [<i class="fas fa-external-link-square-alt"></i> Tabarrok, 2015, "The Case for Getting Rid of Borders—Completely," *The Atlantic*](https://www.theatlantic.com/business/archive/2015/10/get-rid-borders-completely/409501/)
- [<i class="fas fa-podcast"></i> *NPR Planet Money*, 2015, Ep. 654: "When the Boats Arrive"](https://www.npr.org/sections/money/2015/09/30/444800350/episode-654-when-the-boats-arrive)

# Optional Readings (Primary Sources)
- [<i class="fas fa-file-pdf"></i> Borjas, 1994, "The Economics of Immigration"](/readings/Borjas-1994.pdf)
- [<i class="fas fa-file-pdf"></i> Peri, 2018, "Lessons From Immigration Economics"](/readings/Borjas-2018.pdf)
- [<i class="fas fa-file-pdf"></i> Peri, 2009, "Task Specialization, Immigration, and Wages"](/readings/Peri-2009.pdf)
- [<i class="fas fa-file-pdf"></i> Peri, 2016, "Immigrants, Productivity, and Labor Markets"](/readings/Peri-2016.pdf)
- [<i class="fas fa-file-pdf"></i> Autor, Dorn, and Hanson, 2016, "The China Shock: Learningfrom Labor-Market Adjustmentto Large Changes in Trade"](/readings/Autor-Dorn-Hanson-2016.pdf)
- [<i class="fas fa-file-pdf"></i> Card, "How Immigration Affects U.S. Cities", Ch. 6 in *Making Cities Work*](https://books.google.com/books?hl=en&lr=&id=vRKIar9ALjgC&oi=fnd&pg=PA158&dq=david+card+immigration&ots=dAQRL-oRXr&sig=VTfXrrXXIGR9YB7jmuPDPm5KN9k#v=onepage&q=david%20card%20immigration&f=false)
- [<i class="fas fa-external-link-square-alt"></i> Clemens, 2017, "What the Mariel Boatlift of Cuban Refugees Can Teach Us about the Economics of Immigration: An Explainer and a Revelation," *Center for Global Development*](https://www.cgdev.org/blog/what-mariel-boatlift-cuban-refugees-can-teach-us-about-economics-immigration)
- [<i class="fas fa-external-link-square-alt"></i> Pew Research, 2020, "Key Findings About U.S. Immigrants"](https://www.pewresearch.org/fact-tank/2020/08/20/key-findings-about-u-s-immigrants/)