---
title: "1.4 — The Ricardian View of Trade: Formal One-Factor Model — Practice Problems"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
```

- [<i class="fas fa-file-pdf"></i> `Download as PDF`](/practice/1.4-practice-pdf.pdf)
- [<i class="fas fa-file-pdf"></i> `Answer Key`](/practice/1.4-practice-answers.pdf)

Suppose the following facts to set up:

- Home has 100 Laborers
  - Requires 5 workers to make 1wheat
  - Requires 10 workers to make 1 car
  
- Foreign has 200 Laborers
  - Requires 2 workers to make 1 wheat
  - Requires 8 workers to make 1 car

Plot wheat (w) on the horizontal axis and cars (c) on the vertical axis.

## Question 1

Write the equation of each country's production possibilities frontier (PPF).

## Question 2

Graph each country's PPF.

## Question 3

Which country has an *absolute* advantange in producing each good? Why?

## Question 4

Find each country's opportunity cost of producing each good.

## Question 5

Which country has a *comparative* advantage in producing each good? Why?

## Question 6

Which country should specialize in producing which good?

## Question 7

What will the range of possible terms of trade be? 