---
title: "1.12 — New Trade Theory II: Monopolistic Competition — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, September 24, 2020*

# Overview

Today, we finish New Trade Theory.

# Readings

See [today's suggested readings](/reading/1.12-reading).

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.12-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.12-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Assignments: Problem Set 2 and Midterm Exam

[Problem set 2](/assignment/01-problem-set) will be posted very shortly this afternoon, and due by 11:59 PM Sunday September 27 by PDF upload to Blackboard Assignments.

The midterm exam (on 1.1-1.12) will be next week. I will provide more information this week. We will dedicate time for review and questions on class Tuesday, September 29.