---
title: "1.3 — The Ricardian View of Trade: Comparative Advantage — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, August 25, 2020*

# Overview

Today we begin looking at David Ricardo's view of trade, focusing on comparative advantage. We will derive a very simple model of comparative advantage and practice working with it. Next class, we will dive into a more formal Ricardian model that will ultimately be extended into the modern models of international trade over the coming weeks.

# Readings

Please see the suggested (but none are required) [today's readings](/reading/1.3-reading.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.3-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.3-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Practice Problems

Today you will be working on [practice problems](/r/1.3-practice) on simple comparative advantage. Answers will be posted later.

# Assignments

None!