---
title: "1.4 — The Ricardian View of Trade: One-Factor Model — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Thursday, August 27, 2020*

# Overview

Today, we dive into a more formal Ricardian model that will ultimately be extended into the modern models of international trade over the coming weeks.

# Readings

Please see the suggested (but none are required) [today's readings](/reading/1.4-reading). But note the following caution:

**Note:** Feenstra and Taylor dive right into a Ricardian model in Ch. 2 with some advanced features. This throws a lot of moving parts (marginal products of labor, indifference curves, world relative supply and world relative demand curves, export and import curves, etc.) at you very fast. In my experience, and having used different textbooks in the past, is that it is easier if I build more slowly to the full model. This class will be a “simplified Ricardian model” (there is a bit of fudging with marginal products vs. “required labor”) that gets you to see some of the essentials before we layer on additional parts in next class on the “standard” or “neoclassical” trade model. 

So if you are reading the textbook, it won't exactly match up to class for 1-2 weeks 😕

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.4-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.4-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Practice Problems

Answers to last class’ [practice problems](/practice/1.3-practice) on simple comparative advantage are posted on that page. Today you will be working on [practice problems](/practice/1.4-practice) on the Ricardian one-factor model. Answers will be posted later.

# Assignments

None!