---
title: "2.5 — An Intellectual History of Trade III: Better Protectionist Arguments — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Tuesday, October 20, 2020*

# Overview

Today, we continue looking at an intellectual history of trade, discussing new protectionist arguments that emerged since the decline of mercantilism.

# Readings and Discussion Board

See [this week's required readings](/reading/2.5-reading). There are questions to help guide your readings there, and more instructions for the required Blackboard discussion board this week.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/2.5-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/2.5-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Assignments: Discussion Board

This week we will have a discussion board on this week’s readings and general topics. You are expected to post there by Sunday 11:59 PM October 18, and will be graded for your posts. See more on [today’s readings page](/reading/2.5-reading), or the [assignments page](/assignments), for more information.