---
title: "2.7 — The Political Economy of Trade Policy — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Thursday, October 29, 2020* and *Tuesday, November 3, 2020*

# Overview

Today, we look at the politics of trade policy, examining how different groups in a modern democracy have different objectives and face different incentives, culminating in trade policy that concentrates benefits and disperses costs. The tools we use are standard in [“public choice”](https://en.wikipedia.org/wiki/Public_choice) analysis — the economic analysis of politics. You can learn more in [my public economics course](https://publics20.classes.ryansafner.com).

# Readings and Discussion Board

See [this week's required readings](/reading/2.7-reading). There are questions to help guide your readings there, and more instructions for the required Blackboard discussion board this week.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/2.7-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/2.7-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 2:00 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).