---
title: "Problem Set 2"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
#source(file.path(here::here(), "lib", "graphics.R"))
```

*Due by 11:59 PM Sunday, September 27, 2020 by PDF upload in Blackboard Assignments*

- [<i class="fas fa-file-pdf"></i> `Download as PDF`](/assignments/02-problem-set-pdf.pdf)
<!-- [<i class="far fa-life-ring"></i> `Answer Key`](/assignments/01-problem-set-answers.pdf)-->

Please **type** your answers to the following questions in a document and **save as a PDF**^[In MS Word, or Pages, or most word processing software, File -> Save As -> PDF, or File -> Export -> PDF.] to **upload on Blackboard** under Assignments. You may handwrite answers if you will be able to scan/photograph & convert them **to a single PDF**, if they are easily readable, but this is *not preferred*. See my [guide to making a PDF](/reference/#how-to-make-a-pdf-for-submitting-assignments) - an essential skill in the modern world. If you are handwriting answers, you may print the `pdf` above and write on it, or just write on a piece of paper (we only need your answers). 

For the few questions that ask you to draw a **graph**, *try* to do so *on your computer* (use MS Paint, the drawing tools in MS Word or MS Powerpoint, plot points in MS Excel, drawing/notetaking apps, etc.), and save it as an image to include on your homework document. Again, they need not be perfect or to scale, just show that you understand the broad idea. Being able to understand and sketch the graphs is still a very important and useful skill! If all else fails, I will be lenient in grading graph questions if you are unable to technologically include a graph. 

You may work together (and I highly encourage that) but you must turn in your own answers. I grade homeworks 70% for completion, and for the remaining 30%, and one question will be graded for accuracy - so it is best that you try every problem, even if you are unsure how to complete it accurately.

# Concepts and Critical Thinking

## Question 1

What are the sources of comparative advantage according to Hecksher-Ohlin theory, and what types of goods would we expect various countries to import and export?

## Question 2

According to Hecksher-Ohlin theory, what would we expect to happen to factor prices across countries that freely trade?

## Question 3

Explain the Leontief paradox.

## Question 4

How do specific factors and non-specific factors benefit or lose when trade increases? How do exports affect specific and non-specific factors' incomes? How do imports affect specific and non-specific factors' incomes?

## Question 5 

In perfect competition, firms set price equal to marginal cost. Why can't firms do this when there are internal economies of scale?

## Question 6

Respond to the following claim: “The world's poorest countries cannot find anything to export. There is no resource that is abundant--certainly not capital or land, and in small poor nations not even labor is abundant.”

## Question 7

Suppose a country can produce two goods, cloth (X) and food (Y). Explain what happens to the marginal rate of transformation & the PPF, and why, when all countries face (according to different models):

- Constant costs
- Increasing costs
- Decreasing costs

Drawing each example may help.

## Question 8

For each of the following parts, explain whether it is a case of *external* or *internal* economies of scale, and why.

### Part A

Most musical wind instruments in the United States are produced by more than a dozen factories in Elkhart, Indiana.

### Part B

All Hondas sold in the United States are either imported or produced in Marysville, Ohio.

### Part C

All airframes for Airbus, Europe’s only producer of large aircraft, are assembled in a factory in Toulouse, France.

### Part D

Hartford, Connecticut, is the insurance capital of the northeastern United States.


\clearpage

# Problems

## Question 9

Suppose in 2016, the United States imports $400 million in aircraft parts, and exports $500 million in aircraft parts. Calculate the Grubel-Lloyd Index and interpret what your results mean. 

## Question 10

Norway and Sweden have the same preferences, but have very different production opportunities. Norway has a long coast that borders on the north Atlantic, making it relatively more productive in fishing. Sweden has a relatively greater endowment of capital, making it relatively more productive in Volvos (automobiles). 

Graphically illustrate the gains from trade between the two countries using the H-O model, placing fish on the horizontal axis and Volvos on the vertical axis. Be sure to label the equilibria in autarky, specialization, equilibria after trade, the relative price lines, and imports and exports for each country. 